### PR TITLE
"tag_classes" must be treated as css classes 

### PR DESCRIPTION
**Pull request by ginlime**
Syntax for classes was not treated as css classes but as attributes.
It is not good because difference occured between css meta languages.

### CODE REVIEW

**Comment by mk-startialab** [comment]
@davidrios Hey, please give me any reaction!

**Comment by ginlime** [comment]
Oops, the comment shown above is my company-related account...

**Comment by davidrios** [comment]
Do you have a test case or examples for this? Or do you even care still? 😂

**Comment by ginlime** [comment]
Yes, yes! I care about this matter! I waited the reply from you for a long time!
When I reported Pug's syntax highlighting to the VS Code development team, they told me to tell the author of the data...

image

This is the view in VS Code.
The upper pane of this image is described by Pug and the lower pane by SCSS.

The CSS class coloring is different between SCSS and Pug, with "entity.other.attribute-name.class.pug" used in "pug.tmLanguage.json".
So, I replaced this with "entity.other.attribute-name.class.css" and got the same display results in SCSS and Pug as desired.

I have been working on this replacement every time I upgrade VS Code since the VS Code team says they can't handle the "pug.tmLanguage.json" issue.
Not a big task, but still a bit annoying every time...

I'm begging you to align your description with the syntax highlighting of other languages.

Thanks.

**Comment by davidrios** [comment]
Makes sense. Done.

**Pull request closed without merging**
